In [1]:
import pandas as pd
import numpy as np
import warnings 

warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('D:\\nlp models\\fake news\\evaluation.csv', sep=(';'))
df

,Unnamed: 0,title,text,label
0,0,"Sanders back in U.S. Senate, blasts 'coloniali...",WASHINGTON (Reuters) - Democratic U.S. preside...,1
1,1,Kremlin: Syria peoples' congress being 'active...,MOSCOW (Reuters) - A proposal to convene a con...,1
2,2,Oregon Cop Convicted Of Shattering Biker’s Co...,"In a baffling fit of rage, an Oregon State Pol...",0
3,3,Twitter Erupts With Glee Over #CruzSexScandal...,The last thing any politician running for the ...,0
4,4,MUST WATCH VIDEO: Obama Tries To Trash Trump B...,This is too good to miss! Mr. Teleprompter did...,0
...,...,...,...,...
8112,8112,Sean Hannity Throws Hissy Fit After Real Repo...,"Just like Donald Trump, Sean Hannity has a thi...",0
8113,8113,FORMER ASST FBI DIRECTOR WARNS ANTI-TRUMP KABA...,Former Asst. FBI Director James Kallstrom spok...,0
8114,8114,John McCain: Trump’s Attacks On The Press Are...,Donald Trump has declared the media to be the...,0
8115,8115,Syria's Deir al-Zor air base working again: st...,BEIRUT (Reuters) - The Deir al-Zor military ai...,1
8116,8116,"U.S. military releases, withdraws old Islamist...","WASHINGTON (Reuters) - In an awkward reversal,...",1

In [3]:
df = df.drop(columns= 'Unnamed: 0')
df

,title,text,label
0,"Sanders back in U.S. Senate, blasts 'coloniali...",WASHINGTON (Reuters) - Democratic U.S. preside...,1
1,Kremlin: Syria peoples' congress being 'active...,MOSCOW (Reuters) - A proposal to convene a con...,1
2,Oregon Cop Convicted Of Shattering Biker’s Co...,"In a baffling fit of rage, an Oregon State Pol...",0
3,Twitter Erupts With Glee Over #CruzSexScandal...,The last thing any politician running for the ...,0
4,MUST WATCH VIDEO: Obama Tries To Trash Trump B...,This is too good to miss! Mr. Teleprompter did...,0
...,...,...,...
8112,Sean Hannity Throws Hissy Fit After Real Repo...,"Just like Donald Trump, Sean Hannity has a thi...",0
8113,FORMER ASST FBI DIRECTOR WARNS ANTI-TRUMP KABA...,Former Asst. FBI Director James Kallstrom spok...,0
8114,John McCain: Trump’s Attacks On The Press Are...,Donald Trump has declared the media to be the...,0
8115,Syria's Deir al-Zor air base working again: st...,BEIRUT (Reuters) - The Deir al-Zor military ai...,1
8116,"U.S. military releases, withdraws old Islamist...","WASHINGTON (Reuters) - In an awkward reversal,...",1

In [4]:
# Converting everything into lower case

df['text'] = df['text'].apply(lambda x: x.lower())
df['title'] = df['title'].apply(lambda x: x.lower())
df

,title,text,label
0,"sanders back in u.s. senate, blasts 'coloniali...",washington (reuters) - democratic u.s. preside...,1
1,kremlin: syria peoples' congress being 'active...,moscow (reuters) - a proposal to convene a con...,1
2,oregon cop convicted of shattering biker’s co...,"in a baffling fit of rage, an oregon state pol...",0
3,twitter erupts with glee over #cruzsexscandal...,the last thing any politician running for the ...,0
4,must watch video: obama tries to trash trump b...,this is too good to miss! mr. teleprompter did...,0
...,...,...,...
8112,sean hannity throws hissy fit after real repo...,"just like donald trump, sean hannity has a thi...",0
8113,former asst fbi director warns anti-trump kaba...,former asst. fbi director james kallstrom spok...,0
8114,john mccain: trump’s attacks on the press are...,donald trump has declared the media to be the...,0
8115,syria's deir al-zor air base working again: st...,beirut (reuters) - the deir al-zor military ai...,1
8116,"u.s. military releases, withdraws old islamist...","washington (reuters) - in an awkward reversal,...",1

In [5]:
df.isna().sum()

title    0
text     0
label    0
dtype: int64

In [6]:
# Removing punctuations
import string

def remove_punc(txt) :
    return txt.translate(str.maketrans('','',string.punctuation))

df['title'] = df['title'].apply(remove_punc)
df['text'] = df['text'].apply(remove_punc)

In [7]:
def remove_num(txt):
    new = ''
    for i in txt :
        if not i.isdigit():
            new = new + i
    return new

df['title'] = df['title'].apply(remove_num)
df['text'] = df['text'].apply(remove_num)

In [8]:
def remove_emoji(txt):
    new = ''
    for i in txt :
        if i.isascii():
            new = new + i
    return new

df['title'] = df['title'].apply(remove_emoji)
df['text'] = df['text'].apply(remove_emoji)

In [9]:
df

,title,text,label
0,sanders back in us senate blasts colonialism i...,washington reuters democratic us presidential...,1
1,kremlin syria peoples congress being actively ...,moscow reuters a proposal to convene a congre...,1
2,oregon cop convicted of shattering bikers col...,in a baffling fit of rage an oregon state poli...,0
3,twitter erupts with glee over cruzsexscandal ...,the last thing any politician running for the ...,0
4,must watch video obama tries to trash trump bu...,this is too good to miss mr teleprompter didn ...,0
...,...,...,...
8112,sean hannity throws hissy fit after real repo...,just like donald trump sean hannity has a thin...,0
8113,former asst fbi director warns antitrump kabal...,former asst fbi director james kallstrom spoke...,0
8114,john mccain trumps attacks on the press are h...,donald trump has declared the media to be the...,0
8115,syrias deir alzor air base working again state...,beirut reuters the deir alzor military airpor...,1
8116,us military releases withdraws old islamist vi...,washington reuters in an awkward reversal the...,1

In [10]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [11]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Error loading punkt: <urlopen error [Errno 11001]
[nltk_data]     getaddrinfo failed>
[nltk_data] Error loading stopwords: <urlopen error [Errno 11001]
[nltk_data]     getaddrinfo failed>

False

In [12]:
stopwords = set(stopwords.words('english'))
stopwords

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 "we've",
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [13]:
def remove(txt) :
    words = txt.split()
    cleaned = []
    for i in words :
        if not i in stopwords :
            cleaned.append(i)
            
    return ' '.join(cleaned)

df['title'] = df['title'].apply(remove)
df['text'] = df['text'].apply(remove)

In [14]:
# Feature extraction
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()

x_data = df['title'] + df['text']
x = x_data.copy()

x = vectorizer.fit_transform(x)

In [15]:
vectorizer.get_feature_names_out()

array(['aa', 'aaa', 'aadhaar', ..., 'zwo', 'zxmgklb', 'zynga'],
      shape=(90675,), dtype=object)

In [16]:
x_data

0       sanders back us senate blasts colonialism puer...
1       kremlin syria peoples congress actively discus...
2       oregon cop convicted shattering bikers collarb...
3       twitter erupts glee cruzsexscandal rumors twee...
4       must watch video obama tries trash trump turns...
                              ...
8112    sean hannity throws hissy fit real reporter ca...
8113    former asst fbi director warns antitrump kabal...
8114    john mccain trumps attacks press dictators get...
8115    syrias deir alzor air base working state media...
8116    us military releases withdraws old islamist vi...
Length: 8117, dtype: object

In [27]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split

tfidf = TfidfVectorizer()
x_data_encoded = tfidf.fit_transform(x_data)

x_train, x_test, y_train, y_test = train_test_split(x_data_encoded, df['label'], test_size= 0.3, random_state= 42)

In [29]:
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB

svm = SVC(kernel= 'rbf')
lg = LogisticRegression(max_iter= 1000)
nv = MultinomialNB()

In [30]:
svm.fit(x_train,y_train)

SVC()

In [31]:
lg.fit(x_train,y_train)

LogisticRegression(max_iter=1000)

In [32]:
nv.fit(x_train,y_train)

MultinomialNB()

In [33]:
from sklearn.metrics import accuracy_score

print(f'svm : {accuracy_score(y_pred= svm.predict(x_test), y_true=y_test)}')
print(f'Lg : {accuracy_score(y_pred= lg.predict(x_test), y_true=y_test)}')
print(f'nv : {accuracy_score(y_pred= nv.predict(x_test), y_true=y_test)}')

svm : 0.9605911330049262
Lg : 0.9540229885057471
nv : 0.9105090311986864